apiVersion: v1
kind: Service
metadata:
  name: ehpp-service
  labels:
    name: ehpp-service
    app: cpm-ehpp-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8089
  selector:
    name: ehpp-app-pod
    app: cpm-ehpp-app
